---
network_static_routes:
  - to: default
    via: 199.168.97.185

network_static_interfaces:
  - name: eno1
    type: direct
    addrs:
      - 199.168.97.186/29

nomad_host_volumes:
  - name: root_mirror
    path: /data/root_mirror
    read_only: false
