sshd_AuthorizedKeysCommand: /usr/bin/netkeys --ID %u
sshd_AllowGroupsAlways:
  - wheel
  - dante

netlogon_maintenance_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9KC4FQ9SR0LOiZPAeNbiW2bpWHUdACkfMkmZoyuSGRdNazMwOFu3X5UR08if7uVIwbQItMDauxEP8H2zq/ChcOl5ZDbPO9EhIFZmnRCGHB2YtaMeT+w43zbLrnA9FC3Z3wNsNvqzerwaF2nmb1RNaJzLdzEj6dx+rqnPfk2FZj3v0Lgl+A2UAqK0W+uK+l/sS0vMTlWVdTKZuOgmu1nLt3ljeFVYOqWcaeqN+oIOargVA+4yas+N1YTAtNp6ShLqhIaNQS03kXSqHROFT6u5U4Aub7ryQPVyYasriW8dvxWQ41FZ26GcBPL1isMq348Ljgk7W5enGaDc7Xpmy8OMR maldridge@theGibson
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRmN+dYgb49VD7PMQZK/Ohw+uoqp1eV9T/S+zrwVLhG maldridge@deepblue
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD2GUCcjPCYNHVMP9BW2p6yjXqq0OsE/1BtrlF8TuWDJcWoVtZei4AYYg8XQq0QEW5WK66saOnNg2qVV6+VHP7GDPlaaKtkAbcpRBp6qMVcBC0ZyrimV/GPRaYLNOv5FIwFJ1NPhM6xjdIexXYBfPIQwv2RdYuCD+B5tDXIj23OmKH7b6TCsjjD+lJkR1dq9yi8p3EfvFZ/vW7SiGWmg2wTO0I01uekjD/JusqqTAfBYVQ+x/5j9bqpEJFGggPbZOppaUHCjbNzGJD8g9JKyZ4WNniTPwRmYhFGlFcM4d8nggwRLIMT3QWf3ZIi4Zh1f56/94ThVe9JA8542mO4A2/p tox@rootkit
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG2il3IqQU30AgFxVIvg2cQdZKgJNLJ8zkpbifiUH8HQ duncan@tux
