---
void_aquire_certs: true

sshd_passwords: false
sshd_challengeresponse: false

nginx_acme_challenge_path: /var/run/acme/acme-challenge/

void_mesh:
  a-hel-fi.m.voidlinux.org: 192.168.99.100
  b-lej-de.m.voidlinux.org: 192.168.99.101
  c-hel-fi.m.voidlinux.org: 192.168.99.118
  d-hel-fi.m.voidlinux.org: 192.168.99.119
  e-hel-fi.m.voidlinux.org: 192.168.99.120
  f-hel-fi.m.voidlinux.org: 192.168.99.121
  g-hel-fi.m.voidlinux.org: 192.168.99.122
  h-hel-fi.m.voidlinux.org: 192.168.99.123
  i-hel-fi.m.voidlinux.org: 192.168.99.124
  a-sfo3-us.m.voidlinux.org: 192.168.99.103
  a-fsn-de.m.voidlinux.org: 192.168.99.112
  b-hel-fi.m.voidlinux.org: 192.168.99.113
  b-fsn-de.m.voidlinux.org: 192.168.99.115
  a-fra-de.m.voidlinux.org: 192.168.99.117

consul_servers:
  - 192.168.99.120
  - 192.168.99.121
  - 192.168.99.122
