---
- name: Create the reposync group
  group: name=reposync state=present

- name: Create the reposync User
  user: name=reposync state=present

- name: Allow nginx to see the mirror
  user: name=nginx group=reposync

- name: Install rsync
  xbps: pkg=rsync state=present

- name: Create mirror directory
  file: path={{ mirror_path }} state=directory owner=reposync group=reposync mode=0755

- name: Install sync service (1/3)
  file: path=/etc/sv/void-mirror state=directory owner=root group=root mode=0755

- name: Install sync service (2/3)
  template: src=void-mirror.run dest=/etc/sv/void-mirror/run owner=root group=root mode=0755

- name: Install sync service (3/3)
  file: src=/etc/sv/void-mirror dest=/var/service/void-mirror state=link owner=root group=root mode=0755

- name: Install nginx config
  template: src=void-mirror.conf dest=/etc/nginx/sites-available/void-mirror.conf owner=root group=root mode=0644
  notify:
    - nginx

- name: Enable nginx config
  file: src=../sites-available/void-mirror.conf dest=/etc/nginx/sites-enabled/void-mirror.conf state=link
  notify:
    - nginx

- name: Install iptables rules
  template: src=void-mirror.rules dest=/etc/iptables.d/void-mirror.rules owner=root group=root mode=0640
  notify:
    - iptables
